### ISSUE TITLE
Define weights of ScaledSpace at runtime

### ISSUE THREAD

**Issue by clemense** [UNC-Robotics/nigh#2]
Is there any solution to select the weight of a `ScaledSpace` during runtime?  (i.e. `so3weight` and `l2weight` for `SE3Space`)

**Comment by jeffi** [comment]
Yes, there is support for setting the weights at runtime.  (It was incomplete when you wrote the ticket, but now is fully implemented).  Probably the best place to get started is to look at the test cases for scaled spaces.  But it essentially boils down to creating a CartesianSpace around ScaledSpace wrappers of SO3Space and L2Space.

```c++
    using namespace unc::robotics::nigh;
    using Space = CartesianSpace<
        ScaledSpace<SO3Space<double>>,
        ScaledSpace<L2Space<double, 3>>>;
```

Then you have to create a space object that you pass into Nigh's constructor.

```c++
    double so3wt = 12.345;
    double l2wt = 6.789;
    Space space(so3wt, l2wt);
    Nigh<..., Space, ...> nn(space);
```
